### PR TITLE
Adding vars for 8u45

### PR DESCRIPTION
**Pull request by trumant**

### CODE REVIEW

**Comment by spul** [comment]
```
Counting objects: 16, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (16/16), 2.13 KiB | 0 bytes/s, done.
Total 16 (delta 9), reused 0 (delta 0)
To git@github.com:silpion/ansible-java.git
   4f696bc..4316667  master -> master
   48ec833..879d8b1  next -> next
 * [new tag]         0.10.0 -> 0.10.0
```

**Comment by spul** [comment]
Updated galaxy as well.

**Comment by spul** [comment]
trumant: Thank you very much for your PRs. One word to the versioned vars paradigm: Target here is to enable the user to install whatever version required through inventory configuration by providing the shasum and version variables.
Anyway, again, thanks a lot!,

# kraM/spul and silpion.

**Comment by trumant** [comment]
I had these all defined in a playbook consuming the role and wanted to
reduce the number of vars defined there. And I figured that other people
would be upgrading to the latest jdk/jre as well and would appreciate
having these encapsulated within the role.

**Pull request merged**
